import { useEffect, useRef, useState } from "react";
import { Download, FileText } from "lucide-react";
import { publicOfferController } from "./publicOfferController.js";
import "./product-theme-public-offer.css";

const terminal = { accepted: ["已接受 Offer", "您已确认接受该 Offer。"], declined: ["已婉拒 Offer", "您的决定已记录。"], expired: ["Offer 已过期", "该 Offer 已超过回复期限。"], withdrawn: ["Offer 已撤回", "该 Offer 已不再有效。"], superseded: ["Offer 已更新", "该 Offer 已由新版本替代。"], invalid: ["链接无效", "该 Offer 链接无效或已失效。"] };
export function PublicOfferView({ token, controller = publicOfferController }) {
  const [state, setState] = useState({ loading: true, offer: null, error: "" }); const [action, setAction] = useState(""); const [startDate, setStartDate] = useState(""); const [reason, setReason] = useState(""); const [confirm, setConfirm] = useState(""); const [submitting, setSubmitting] = useState(false); const dialogRef = useRef(null);
  useEffect(() => { let live = true; controller.load(token).then((offer) => live && setState({ loading: false, offer, error: "" })).catch(() => live && setState({ loading: false, offer: null, error: "暂时无法加载 Offer，请稍后重试。" })); return () => { live = false; }; }, [controller, token]);
  useEffect(() => { if (confirm) dialogRef.current?.focus(); }, [confirm]);
  if (state.loading) return <main className="public-offer-page" role="status" aria-live="polite">正在加载 Offer…</main>;
  const offer = state.offer; const terminalState = !offer || terminal[offer.status] ? (offer?.status || "invalid") : "";
  if (terminalState) { const [title, copy] = terminal[terminalState]; return <main className="public-offer-page public-offer-terminal"><h1>{title}</h1><p>{copy}</p></main>; }
  async function submit() { if (submitting || (action === "accepted" && !startDate)) return; setSubmitting(true); try { const next = await controller.respond(token, action === "accepted" ? { decision: action, expected_start_date: startDate } : { decision: action, reason: reason || null }); setState({ loading: false, offer: { ...offer, ...next, status: action }, error: "" }); setStartDate(""); setReason(""); setConfirm(""); } catch { setState({ ...state, error: "提交未完成，请稍后重试。" }); setSubmitting(false); } }
  return <main className="public-offer-page"><header className="public-offer-header"><span>BeyondCandidate</span><strong>{offer.companyName}</strong></header><section className="public-offer-content"><p className="public-offer-eyebrow">Offer 确认</p><h1>{offer.jobTitle || "职位 Offer"}</h1>{offer.location && <p>{offer.location}</p>}<dl><div><dt>回复截止日期</dt><dd>{offer.deadline || "请联系招聘团队"}</dd></div>{offer.contact && <div><dt>招聘联系人</dt><dd>{offer.contact}</dd></div>}</dl>{offer.summary && <section className="public-offer-summary"><h2>Offer 摘要</h2><p>{offer.summary}</p></section>}<section className="public-offer-pdf"><h2><FileText size={18} /> Offer 文件</h2><iframe title="Offer PDF 预览" src={controller.pdfUrl(token)} /><a className="button secondary" href={controller.pdfUrl(token)} download><Download size={16} />下载 Offer PDF</a></section><div className="public-offer-actions"><button className="button" type="button" disabled={submitting} onClick={() => setConfirm("accepted")}>接受 Offer</button><button className="button secondary" type="button" disabled={submitting} onClick={() => setConfirm("declined")}>婉拒 Offer</button></div>{state.error && <p className="public-offer-error" role="alert">{state.error}</p>}</section>{confirm && <div className="public-offer-dialog-backdrop"><section className="public-offer-dialog" role="dialog" aria-modal="true" aria-labelledby="offer-confirm-title" tabIndex="-1" ref={dialogRef}><h2 id="offer-confirm-title">{confirm === "accepted" ? "确认接受 Offer" : "确认婉拒 Offer"}</h2>{confirm === "accepted" ? <label>预计入职日期<input name="expected_start_date" type="date" required value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label> : <label>原因（可选）<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label>}<div><button className="button secondary" type="button" disabled={submitting} onClick={() => setConfirm("")}>取消</button><button className="button" type="button" disabled={submitting || (confirm === "accepted" && !startDate)} onClick={() => { setAction(confirm); void submit(); }}>{submitting ? "正在提交…" : "确认提交"}</button></div></section></div>}</main>;
}
